NDefines.NDiplomacy.MAX_DUCHIES_LEGALLY_HELD = 4
NDefines.NDiplomacy.DEMESNE_BASE_MAX_SIZE = 6.0
NDefines.NDiplomacy.DEMESNE_MAX_SIZE_DUKE_MULT = 1.15
NDefines.NDiplomacy.DEMESNE_MAX_SIZE_KING_MULT = 5.0
NDefines.NDiplomacy.DEMESNE_MAX_SIZE_EMPEROR_MUL = 6.0
NDefines.NDiplomacy.DEMESNE_MAX_SIZE_STEWARDSHIP_MULT = 0.20
NDefines.NCharacter.MAX_WARDS_PER_GUARDIAN = 4
